apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.fullname" . }}-server
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    component: server
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: 8080
    protocol: TCP
    name: http
  - port: {{ .Values.service.grpcPort }}
    targetPort: 50051
    protocol: TCP
    name: grpc
  {{- if .Values.prometheus.enabled }}
  - port: {{ .Values.service.metricsPort }}
    targetPort: {{ .Values.prometheus.port }}
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    {{- include "observability.selectorLabels" . | nindent 4 }}
    component: server
